id: I6D6B664E
legacy_id: P009426
ocr_import_info:
  bdrc_scan_id: W1KG14646
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T00:05:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:10:41.128016+00:00'
last_modified: 2022-08-27 13:11:04.384574
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14646
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14646
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲིས་ལན་དོན་གཅིག་མ། དམ་ཆོས་དགོངས་གཅིག་གི་མཛེས་རྒྱན།
  author: སྤྱན་སྔ་དཀོན་མཆོག་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9507015356473915
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG15706:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15706
      total_pages: 226
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15706.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9507015356473915
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
