id: P009426
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14646
  title: དྲིས་ལན་དོན་གཅིག་མ། དམ་ཆོས་དགོངས་གཅིག་གི་མཛེས་རྒྱན།
  author: ''
  volumes:
    18263c91b0b549d682db620695528720:
      image_group_id: I1KG15706
      title: ''
      volume_number: 1
      total_pages: 226
